import React from "react";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>Web App | About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>About page is here...</div>
    </>
  );
};

export default About;
