import React from "react";
import Head from "next/head";
import styles from "../styles/about.module.css";
import Image from "next/image";
import image from "../public/about.gif";

const About = () => {
  return (
    <>
      <Head>
        <title>Web App | About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1>About our Blog App</h1>
        <hr />
        <h2>Introduction</h2>

        <p>
          <p>
            <Image
              src={image}
              className={styles.image}
              alt="About page "
              width={300}
            ></Image>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia
            autem sed facilis quia consectetur magni reprehenderit quo,
            obcaecati iste incidunt quis quaerat, corporis voluptatum omnis
            similique nisi unde quos, iusto fugiat tenetur eaque. Ullam,
            sapiente illo dolorem, minus saepe consequuntur esse perferendis
            optio cumque temporibus impedit maxime dolorum voluptatum
            voluptatibus consectetur neque, quam nemo nihil quia aspernatur?
            Nobis, harum est.
          </p>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum
            minus ipsam quidem esse impedit assumenda iusto iste fuga beatae
            voluptatibus doloribus iure, officia facere obcaecati delectus enim.
            Atque culpa omnis eveniet accusamus, veniam voluptates porro labore
            sed iure amet officia! Dolorem provident repellendus corrupti
            dolores, mollitia incidunt. Itaque eligendi, iste quasi eos,
            consequatur placeat, voluptates soluta a nesciunt amet ipsum nisi ut
            quibusdam expedita dolorem reiciendis dicta molestiae numquam sequi
            quae. Quos odit est aut unde harum, iure impedit dolore nesciunt
            recusandae.
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus
            quidem consequuntur tenetur!
          </p>
        </p>
      </div>
    </>
  );
};

export default About;
