import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web App | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul className={styles.nav}>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h3 className={styles.title}>Welcome to Web App</h3>

        <p className={styles.description}>
          A blog by the coders for the coders.
        </p>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
