import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import image from "../public/img.jpg";
import Blog from "./blog";

export default function Home() {
  return (
    <div>
      <style jsx>
        {`
          h2 {
            font-size: 29px;
          }
          h3 {
            font-size: 22px;
          }
          .blogItem p {
            margin-top: 0px;
          }
          .blogItem h3 {
            margin-bottom: 0px;
          }
        `}
      </style>
      <Head>
        <title>Web App | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Blog World</h1>
        <Image
          src={image}
          alt="home page "
          width={400}
          className={styles.image}
        ></Image>

        <p className={styles.description}>
          A blog by the coders for the coders.
        </p>

        <Blog />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
