import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import image from "../public/img.jpg";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 29px;
          }
          h3 {
            font-size: 22px;
          }
          .blogItem p {
            margin-top: 0px;
          }
          .blogItem h3 {
            margin-bottom: 0px;
          }
        `}
      </style>
      <Head>
        <title>Web App | Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul className={styles.nav}>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blogs</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h3 className={styles.title}>Welcome to Web App</h3>
        <Image
          src={image}
          alt="home page "
          width={400}
          className={styles.image}
        ></Image>

        <p className={styles.description}>
          A blog by the coders for the coders.
        </p>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript.</h3>
            <p>
              Javascript is the language used to design the logics for the web.
            </p>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
